name:                abnfu
version:             0.1.0.0
github:              "lancelet/abnfu"
license:             BSD3
author:              "Jonathan Merritt"
maintainer:          "j.s.merritt@gmail.com"
copyright:           "2018 Jonathan Merritt"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/abnfu#readme>

dependencies:
- base >= 4.7 && < 5
- case-insensitive
- containers
- hedgehog
- megaparsec
- parser-combinators
- semigroups
- tasty
- tasty-hedgehog
- text

ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmissing-import-lists

_exe-ghc-options: &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

library:
  source-dirs: src

executables:
  abnfu-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:         *exe-ghc-options
    dependencies:
    - abnfu

tests:
  abnfu-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:         *exe-ghc-options
    dependencies:
    - abnfu
